version: '4.1'
services:
  db:
    image: postgres:14.2-alpine
    ports:
      - "2222:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres